# Site settings
title: Corinthiale
#email: hail@hydra.420
description: > # this means to ignore newlines until "baseurl:"
  The official site of the Corinthiale
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://corinthiale.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: corinthiale

# Build settings
markdown: kramdown
